-- AlterEnum
ALTER TYPE "Amphoe" RENAME VALUE 'MUEANG_SARABURI' TO 'เมืองสระบุรี';
ALTER TYPE "Amphoe" RENAME VALUE 'KAENG_KHOI' TO 'แก่งคอย';
ALTER TYPE "Amphoe" RENAME VALUE 'NONG_KHAE' TO 'หนองแค';
ALTER TYPE "Amphoe" RENAME VALUE 'WIHAN_DAENG' TO 'วิหารแดง';
ALTER TYPE "Amphoe" RENAME VALUE 'NONG_SAENG' TO 'หนองแซง';
ALTER TYPE "Amphoe" RENAME VALUE 'BAN_MO' TO 'บ้านหมอ';
ALTER TYPE "Amphoe" RENAME VALUE 'DON_PHUT' TO 'ดอนพุด';
ALTER TYPE "Amphoe" RENAME VALUE 'NONG_DON' TO 'หนองโดน';
ALTER TYPE "Amphoe" RENAME VALUE 'PHRA_PHUTTHABAT' TO 'พระพุทธบาท';
ALTER TYPE "Amphoe" RENAME VALUE 'SAO_HAI' TO 'เสาไห้';
ALTER TYPE "Amphoe" RENAME VALUE 'MUAK_LEK' TO 'มวกเหล็ก';
ALTER TYPE "Amphoe" RENAME VALUE 'WANG_MUANG' TO 'วังม่วง';
ALTER TYPE "Amphoe" RENAME VALUE 'CHALOEM_PHRA_KIAT' TO 'เฉลิมพระเกียรติ';
